language: java
dist: trusty
addons:
  sonarcloud:
    organization: rafaelspinto-github
    token:
      secure: IMmNIAVaikjaCp+meteBQPai96T79MtRyALyQ7fYvG+0kIJdiKeSf9QNlVYNnUcRN1t50cMZ2J4kndPpZ6StAHc50RSXBLPVr0XnB4aeIjeCUsfbofE1Vtwrvbw6QHUlE8vlQ6VNUCC9x9rcbDbHfW+NQbaY526+tuT1l/J3Aou8HUQDywusPePApg2xFtYuRh3nfKwsv1VGJGNV0yrDRms2LJQZA/v+oKP1K/NatPSWCIRDnCNJkPCSHs4UqYKEzzKTZEddAqjTvMLbpKBmV7SUbXS27nNfo2fJ9Nf/7sZJBpOl3MF+dxvA70BycLqqU8wxbuubqeZGF+USEa7TT9ItzLTm//0w5t91Mfe/VB6nPRZQCl5hKZ1NT8iBeLtt0jlYp0+9b1D7mXUpBS3EV1VAlIy62REUVmIZxkrgcLqsJ+WYU3xEAoHbMNmpPOgI4lt3LcJE1p4yxaUvd+v17wK0mv0okvemZukPUNHfCJtNUiw5V34LKmJF1EMbYikOoh/Dixtpp18FDWWpd+qVaS4sEIeY07NvVW42Wi5RU5/oS07v6jaVcnDz1/503MVOcVHIW8q+o75rZ91RM7ffVY3UvTBazT7qtRJAOgpaSAtyZMj4T3IaGEKBW3Aj2n8XxVf65/qrIozjBxnrnbHo6aTZlCbbnsYM/i7bptu5Zd0=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
- mvn test
